Use getFontLoaderConfig to optimize font loading
bigcommerce/cornerstone pull request #1895
Opened 2020-11-05 14:17 UTC by bookernath

#### What?

The previous implementation of Web Font Loader would not respond to custom fonts selected in Page Builder. This fixes that, by pulling in the helper.

2020-11-05 15:20 UTC, bookernath commented
Test results proving no negative impact to CLS:

### Lighthouse on local Chrome:

Mobile:
![image](https://user-images.githubusercontent.com/8922457/98259527-de70b700-1f47-11eb-87c2-9b3102b6a022.png)
Desktop: 
![image](https://user-images.githubusercontent.com/8922457/98259574-ed576980-1f47-11eb-8013-984a9b1d48b9.png)

### Lighthouse on web.dev:
![image](https://user-images.githubusercontent.com/8922457/98259757-21328f00-1f48-11eb-9e4d-9fc97625157c.png)


### WebPageTest:
![image](https://user-images.githubusercontent.com/8922457/98259722-14ae3680-1f48-11eb-868b-5e4e6e7de5cd.png)

2020-11-05 15:32 UTC, yurytut1993 commented
@bookernath  LGTM &#128077; 
can you please also update changelog?

2020-11-05 16:50 UTC, bookernath commented
Here are results using just `display=block` approach:

### Lighthouse on local Chrome:

Mobile:
![image](https://user-images.githubusercontent.com/8922457/98270530-93a96c00-1f54-11eb-96ad-eb7e49d6aade.png)

Desktop: 
![image](https://user-images.githubusercontent.com/8922457/98270727-c5bace00-1f54-11eb-89fe-0e3ccc512cc0.png)


### Lighthouse on web.dev:
![image](https://user-images.githubusercontent.com/8922457/98270700-bd629300-1f54-11eb-80b2-f583143b0028.png)


### WebPageTest:
![image](https://user-images.githubusercontent.com/8922457/98270655-b176d100-1f54-11eb-9e55-61ac5454b6e6.png)

2020-11-06 13:04 UTC, BC-tymurbiedukhin requested changes

2020-11-06 13:04 UTC, BC-tymurbiedukhin commented on CHANGELOG.md
> +- Switch font loading to use display=block to improve Lighthouse results [#1895](https://github.com/bigcommerce/cornerstone/pull/1895)
Should we remove this from draft as these items included in 4.12

2020-11-06 13:04 UTC, BC-tymurbiedukhin commented on CHANGELOG.md
> +- Reduce lodash usage in compare-products.js and image-gallery.js [#1894](https://github.com/bigcommerce/cornerstone/pull/1894)
Could we update the title for this changelog item?

2020-11-19 13:53 UTC, closed without merging