fix(storefront): BCTHEME-912 Admin Bar displays regardless of setting
bigcommerce/cornerstone pull request #2144
Opened 2021-11-15 12:00 UTC by bc-vlad-dlogush

#### What?

This PR removes setting Admin Bar from Cornerston because that setting will actually not do anything currently and is not controlled by the Theme anymore.

#### Tickets / Documentation

- [BCTHEME-912](https://jira.bigcommerce.com/browse/BCTHEME-912)

#### Screenshots (if appropriate)

![with AdminBar](https://user-images.githubusercontent.com/83779098/141778125-0b1e1eb1-9604-41ae-9d17-dded2718497f.png)
<img width="581" alt="without AdminBar" src="https://user-images.githubusercontent.com/83779098/141778127-d0a5779c-a147-4435-b9d1-5213994dfd15.png">

2021-11-15 12:54 UTC, BC-krasnoshapka requested changes
@bc-vlad-dlogush I found usage of show-admin-bar in /templates/layout/base.html, please remove it also.

2021-11-15 14:31 UTC, BC-krasnoshapka commented
https://github.com/bigcommerce/cornerstone/blob/84b4231ce510fcd0509bcaaf1b7540bc62dd2351/assets/js/theme/global.js#L33 - also can this be removed? Please test that admin bar works correctly without this code.

2021-11-16 17:15 UTC, bc-vlad-dlogush commented
> https://github.com/bigcommerce/cornerstone/blob/84b4231ce510fcd0509bcaaf1b7540bc62dd2351/assets/js/theme/global.js#L33
> 
> - also can this be removed? Please test that admin bar works correctly without this code.

@BC-krasnoshapka Done!

2021-11-17 08:34 UTC, BC-krasnoshapka approved these changes

2021-11-17 09:43 UTC, bc-alexsaiannyi approved these changes

2021-11-17 10:16 UTC, bc-yevhenii-buliuk approved these changes

2021-11-19 08:53 UTC, yurytut1993 approved these changes

2021-12-02 16:54 UTC, bc-azvierieva approved these changes

2021-12-03 17:05 UTC, merged