fix(storefront): BCTHEME-1748 Check lang helpers usage and existence of key in translation file
bigcommerce/cornerstone pull request #2403
Opened 2023-11-28 09:37 UTC by bc-vlad-dlogush

#### What?

This PR fixes an issue with displaying warnings in the terminal.

#### Tickets / Documentation

- [BCTHEME-1748](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1748)

#### Screenshots / Screen Recording 

**Before**

https://github.com/bigcommerce/cornerstone/assets/83779098/a550d0e5-54a1-4e8b-9729-98df60777afb

**After**

<img width="1303" alt="Screenshot 2023-11-28 at 11 16 02" src="https://github.com/bigcommerce/cornerstone/assets/83779098/6ee5d370-92e9-4ebb-a3f3-4c996043b422">

[BCTHEME-1748]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-11-28 10:02 UTC, bc-vlad-dlogush commented
By default, translations from `en.json` were taken and the storefront was displayed correctly, but with the help of lang helper, warnings were displayed in the terminal about the lack of translations for certain phrases in `en-CA.json`, so translations from en.json were used to avoid warnings. Everything is fine here

We have a similar situation with fr.json and `fr-CA.json` and everything works fine too, but there are no warnings in the terminal about the lack of translations for certain phrases of `fr-CA.json`.

2023-11-28 10:31 UTC, BC-krasnoshapka commented
@VladDlogush both `en-CA` and `fr-CA` are not officially supported by BigCommerce, automatic translations are not delivered and storefront should fallback to `en` and `fr` respectfully. Thus we can delete both files. Please check that errors in CLI are gone.

2023-11-28 10:33 UTC, BC-krasnoshapka requested changes
@VladDlogush both `en-CA` and `fr-CA` are not officially supported by BigCommerce, automatic translations are not delivered and storefront should fallback to `en` and `fr` respectfully. Thus we can delete both files. Please check that errors in CLI are gone.

2023-11-28 10:39 UTC, bc-vlad-dlogush commented
@BC-krasnoshapka Done!

2023-11-28 10:47 UTC, BC-krasnoshapka approved these changes

2023-11-28 11:37 UTC, bc-vlad-dlogush commented on CHANGELOG.md
> +- Check lang helpers usage and existence of key in translation file [#2398](https://github.com/bigcommerce/cornerstone/pull/2398)
Done!

2023-11-28 11:38 UTC, bc-yevhenii-buliuk approved these changes

2023-11-29 18:56 UTC, yurytut1993 approved these changes

2023-12-06 09:36 UTC, merged